module.exports = {
    logText: () => {},
    moveLocalText: () => {},
    reports: () => {},
    fileDialog: () => {},
    windowsNotifications: () => {},
    reminders: () => {},
    getIconPath: () => {},
    getWarnIconPath: () => {},
    getVersion: () => {},
    getElectronVersion: () => {},
    getChromeVersion: () => {},
    registerHotKey: () => {},
    unregisterHotKey: () => {},
    showMessageBox: () => {},
    getSettings: () => {},
    setSetting: () => {},
    postLog: () => {}
}